<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
/**
 * Defaults
 */
$GLOBALS['TL_LANG']['pct_themer']['headline'] 					= 'PCT Theme Export: %s';
$GLOBALS['TL_LANG']['pct_themer']['infos']['collecting_data'] 	= 'Sammle Daten...';
$GLOBALS['TL_LANG']['pct_themer']['infos']['file_created'] 		= 'Das Demo-Template (%s) wurde in /templates gespeichert.';
$GLOBALS['TL_LANG']['pct_themer']['submit_complete'] 			= 'Fertigstellen';
$GLOBALS['TL_LANG']['pct_themer']['submit_download'] 			= 'Download';
$GLOBALS['TL_LANG']['pct_themer']['alert_no_theme_selected'] 	= 'Export nicht möglich, da für diese Wurzelseite kein Theme ausgewählt ist!';
$GLOBALS['TL_LANG']['pct_themer']['import_success'] 			= 'Theme Demo-Daten erfolgreich angelegt.';
$GLOBALS['TL_LANG']['pct_themedesigner']['backend_info']		= '<span style="line-height:24px;">ThemeDesigner ist <strong>aktiv</strong>. Deaktivieren Sie den ThemeDesigner, wenn die Website "live" gehen soll.</span>';
$GLOBALS['TL_LANG']['pct_themedesigner']['backend_info_green']	= '<span style="line-height:24px;">ThemeDesigner ist im <strong>Live-Modus</strong>.';

$GLOBALS['TL_LANG']['pct_themedesigner']['nosave_info']			= 'Sie haben noch keine Version gespeichert.';

/**
 * Status
 */
$GLOBALS['TL_LANG']['pct_theme_installer']['copy_files_completed']	= 'Installation (%s) : Kopieren der Daten abgeschlossen.';
