<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
/**
 * Errors
 */
$GLOBALS['TL_LANG']['XPT']['pct_theme_installer']['unzip_error'] 			= 'Das Entpacken der Datei %s ist fehlgeschlagen.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_installer']['zip_content_error'] 		= 'Pflichtinhalte (%s) in dem entpackten Verzeichnis nicht gefunden.';