<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
/**
 * Errors
 */
$GLOBALS['TL_LANG']['pct_theme_installer']['label_key'] 		= 'Lizenzschlüssel / Bestellnummer';
$GLOBALS['TL_LANG']['pct_theme_installer']['label_email'] 		= 'Bestell-E-Mail-Adresse';
$GLOBALS['TL_LANG']['pct_theme_installer']['value_submit'] 		= 'Lizenz abfragen';
